### ISSUE TITLE
Php 8.1 install error

### ISSUE THREAD

**Issue by SeditioCMS** [sedteam/Seditio#68]
`[15-Sep-2022 15:34:51 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:34:51 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
[15-Sep-2022 15:34:51 Europe/Minsk] PHP Warning:  Undefined array key "redirmode" in /home/xxxxx/public_html/system/functions.php on line 3686
[15-Sep-2022 15:41:26 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:41:26 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
[15-Sep-2022 15:41:26 Europe/Minsk] PHP Warning:  Undefined array key "redirmode" in /home/xxxxx/public_html/system/functions.php on line 3686
[15-Sep-2022 15:41:29 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:41:29 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
[15-Sep-2022 15:41:29 Europe/Minsk] PHP Warning:  Undefined array key "redirmode" in /home/xxxxx/public_html/system/functions.php on line 3686
[15-Sep-2022 15:41:43 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:41:43 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
[15-Sep-2022 15:41:43 Europe/Minsk] PHP Warning:  Undefined array key "redirmode" in /home/xxxxx/public_html/system/functions.php on line 3686
[15-Sep-2022 15:42:21 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:42:21 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
[15-Sep-2022 15:42:21 Europe/Minsk] PHP Warning:  Undefined array key "redirmode" in /home/xxxxx/public_html/system/functions.php on line 3686
[15-Sep-2022 15:42:55 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:42:55 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
[15-Sep-2022 15:42:55 Europe/Minsk] PHP Warning:  Undefined array key "redirmode" in /home/xxxxx/public_html/system/functions.php on line 3686
[15-Sep-2022 15:42:55 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:42:55 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
[15-Sep-2022 15:42:55 Europe/Minsk] PHP Warning:  Undefined array key "redirmode" in /home/xxxxx/public_html/system/functions.php on line 3686
[15-Sep-2022 15:42:55 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:42:55 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
[15-Sep-2022 15:42:55 Europe/Minsk] PHP Warning:  Undefined array key "redirmode" in /home/xxxxx/public_html/system/functions.php on line 3686
[15-Sep-2022 15:43:26 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:43:26 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
[15-Sep-2022 15:43:26 Europe/Minsk] PHP Warning:  Undefined array key "redirmode" in /home/xxxxx/public_html/system/functions.php on line 3686
[15-Sep-2022 15:44:40 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:44:40 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
[15-Sep-2022 15:44:40 Europe/Minsk] PHP Warning:  Undefined array key "redirmode" in /home/xxxxx/public_html/system/functions.php on line 3686
[15-Sep-2022 15:45:06 Europe/Minsk] PHP Warning:  require(/home/xxxxx/public_html/datas/config.php): Failed to open stream: No such file or directory in /home/xxxxx/public_html/system/core/page/page.php on line 25
[15-Sep-2022 15:45:06 Europe/Minsk] PHP Fatal error:  Uncaught Error: Failed opening required '/home/xxxxx/public_html/datas/config.php' (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php') in /home/xxxxx/public_html/system/core/page/page.php:25
Stack trace:
#0 /home/xxxxx/public_html/index.php(63): include_once()
#1 {main}
  thrown in /home/xxxxx/public_html/system/core/page/page.php on line 25
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_members" in /home/xxxxx/public_html/system/functions.admin.php on line 711
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_members" in /home/xxxxx/public_html/system/functions.admin.php on line 711
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_members" in /home/xxxxx/public_html/system/functions.admin.php on line 711
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_members" in /home/xxxxx/public_html/system/functions.admin.php on line 711
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "request_uri" in /home/xxxxx/public_html/system/functions.php on line 3210
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.php on line 3210
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "request_uri" in /home/xxxxx/public_html/system/functions.php on line 3210
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Warning:  Undefined array key "Auth_guests" in /home/xxxxx/public_html/system/functions.admin.php on line 687
[15-Sep-2022 15:48:55 Europe/Minsk] PHP Deprecated:  str_split(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxxxx/public_html/system/functions.admin.php on line 43
[15-Sep-2022 15:49:05 Europe/Minsk] PHP Warning:  Undefined array key "sefurls" in /home/xxxxx/public_html/system/functions.php on line 4741
[15-Sep-2022 15:49:05 Europe/Minsk] PHP Warning:  Undefined array key "abs_url" in /home/xxxxx/public_html/system/functions.php on line 4806
`

**Comment by avego** [comment]
![image](https://user-images.githubusercontent.com/1747178/190445417-23d189e9-e5bb-44ed-bc7c-ae0442a1cd63.png)
Maybe you have a problem here?
Where is config.php?

**Comment by avego** [comment]
https://user-images.githubusercontent.com/1747178/190445747-cd5bc0ff-a385-4d44-b7b2-2b9d239333ee.mp4

**Comment by SeditioCMS** [comment]
config.php should create itself on auto install
I'll try again at 8.

**Comment by SeditioCMS** [comment]
https://streamable.com/02ldig
where is the problem

**Comment by avego** [comment]
![image](https://user-images.githubusercontent.com/1747178/194521320-8d2b1d97-9bd4-4f08-b387-5c1c91c210f4.png)
What do you have in apache error.log ?

**Comment by SeditioCMS** [comment]
**I solved it by entering the MySQL password, but the slider gives an error.** **and other errors.**

[07-Oct-2022 11:46:54 UTC] PHP Warning:  Undefined array key "sefurls" in C:\MAMP\htdocs\sed178\system\functions.php on line 4757
[07-Oct-2022 11:46:54 UTC] PHP Warning:  Undefined array key "abs_url" in C:\MAMP\htdocs\sed178\system\functions.php on line 4822
[07-Oct-2022 11:46:54 UTC] PHP Warning:  Undefined array key "redirmode" in C:\MAMP\htdocs\sed178\system\functions.php on line 3702
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "Auth_guests" in C:\MAMP\htdocs\sed178\system\functions.admin.php on line 692
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "mainurl" in C:\MAMP\htdocs\sed178\system\functions.php on line 2189
[07-Oct-2022 11:47:19 UTC] PHP Warning:  Undefined array key "maintitle" in C:\MAMP\htdocs\sed178\system\functions.php on line 2189
[07-Oct-2022 11:48:16 UTC] PHP Warning:  Undefined array key "sefurls" in C:\MAMP\htdocs\sed178\system\functions.php on line 4757
[07-Oct-2022 11:48:16 UTC] PHP Warning:  Undefined array key "abs_url" in C:\MAMP\htdocs\sed178\system\functions.php on line 4822
[07-Oct-2022 11:48:16 UTC] PHP Warning:  Undefined array key "redirmode" in C:\MAMP\htdocs\sed178\system\functions.php on line 3702
[07-Oct-2022 11:48:37 UTC] PHP Warning:  Undefined array key "mainurl" in C:\MAMP\htdocs\sed178\system\functions.php on line 2189
[07-Oct-2022 11:48:37 UTC] PHP Warning:  Undefined array key "maintitle" in C:\MAMP\htdocs\sed178\system\functions.php on line 2189
[07-Oct-2022 11:49:29 UTC] PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in C:\MAMP\htdocs\sed178\system\install\install.main.php:125
Stack trace:
#0 C:\MAMP\htdocs\sed178\system\install\install.main.php(125): fwrite(false, '<?PHP\n\n/* =====...')
#1 C:\MAMP\htdocs\sed178\system\install\install.php(44): require('C:\\MAMP\\htdocs\\...')
#2 C:\MAMP\htdocs\sed178\index.php(63): include_once('C:\\MAMP\\htdocs\\...')
#3 {main}
  thrown in C:\MAMP\htdocs\sed178\system\install\install.main.php on line 125
[07-Oct-2022 11:49:31 UTC] PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in C:\MAMP\htdocs\sed178\system\install\install.main.php:125
Stack trace:
#0 C:\MAMP\htdocs\sed178\system\install\install.main.php(125): fwrite(false, '<?PHP\n\n/* =====...')
#1 C:\MAMP\htdocs\sed178\system\install\install.php(44): require('C:\\MAMP\\htdocs\\...')
#2 C:\MAMP\htdocs\sed178\index.php(63): include_once('C:\\MAMP\\htdocs\\...')
#3 {main}
  thrown in C:\MAMP\htdocs\sed178\system\install\install.main.php on line 125
[07-Oct-2022 11:49:34 UTC] PHP Warning:  Undefined variable $sed_dic in C:\MAMP\htdocs\sed178\system\common.php on line 672
[07-Oct-2022 11:50:18 UTC] PHP Warning:  Undefined array key "Copyright" in C:\MAMP\htdocs\sed178\system\core\admin\admin.plug.inc.php on line 94
[07-Oct-2022 11:50:18 UTC] PHP Warning:  Undefined array key "Notes" in C:\MAMP\htdocs\sed178\system\core\admin\admin.plug.inc.php on line 95
[07-Oct-2022 11:50:22 UTC] PHP Warning:  Trying to access array offset on value of type null in C:\MAMP\htdocs\sed178\system\database.mysqli.php on line 256
[07-Oct-2022 11:50:23 UTC] PHP Warning:  Undefined variable $sed_dic in C:\MAMP\htdocs\sed178\system\common.php on line 672
